### ISSUE TITLE
Comment here to be added as a collaborator! 

### ISSUE THREAD

**Issue by brianamarie** [githubschool/apr-9#1]
What would you like to learn?

**Comment by RobinBreyl** [comment]
Solid understanding of Git and GitHub concepts

**Comment by rh851** [comment]
This comment intentionally left blank.

**Comment by flogat** [comment]
Hi :-)

**Comment by GH-mv** [comment]
How work seperation of rules and accesses

**Comment by schomarschomar** [comment]
Learning the GitHub vocabulary

**Comment by katjalinke** [comment]
How can I maintain proper System documentation on Github?

**Comment by if338** [comment]
Get an understanding what features and concepts are available in GitHub beside software repository

**Comment by gerald8858** [comment]
Learning by doing

**Comment by Jessehaslam1983** [comment]
Hi
