### ISSUE TITLE
Things to do in Goa, India

### ISSUE THREAD

**Issue by clearsab** [githubschool/apr-9#16]
Things to do in Goa, India
North Goa:

1. Beaches to visit
- Candolim
- Morjm
- Calangute
- Vagator
South Goa
St.Francis Cathedral

2. To eat
- Sea Food
- Traditional Goan Curry
- Portuguese Vindaloo

3. Explore
- Night life at Calangute Beach
- Street shopping at the flea market

**Comment by rh851** [comment]
Isn't Goa a bit far from Mumbay?

**Comment by clearsab** [comment]
Yes around 300 kms from Mumbai
